version: "3.4"

services:
  php:
    build:
      context: php
    container_name: php
    hostname: php
    volumes:
      - .:/var/www/html/
    networks:
      - localnet

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    volumes:
      - .:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - localnet


networks:
  localnet:
    driver: bridge